feat: create branch for release

diff --git a/.github/workflows/maven-bulk-release-core-services.yml b/.github/workflows/maven-bulk-release-core-services.yml
--- a/.github/workflows/maven-bulk-release-core-services.yml
+++ b/.github/workflows/maven-bulk-release-core-services.yml
@@ -64,22 +64,22 @@ jobs:
       summary_content: ${{ steps.save-summary.outputs.content }}
 
     steps:
-#      - name: Validate branch name
-#        if: github.ref_name != 'main' && !startsWith(github.ref_name, 'lts/')
-#        run: |
-#          echo "::error title=Invalid Branch::Branch '${{ github.ref_name }}' is not allowed. Only 'main' or branches starting with 'lts/' are permitted."
-#          echo "Error: Invalid branch '${{ github.ref_name }}'"
-#          echo "Only 'main' or branches starting with 'lts/' are allowed"
-#          exit 1
-#
-#      - name: Validate LTS branch version increment
-#        if: startsWith(github.ref_name, 'lts/') && inputs.versionIncrementType != 'patch'
-#        run: |
-#          echo "::error title=Invalid Version Increment::LTS branches can only increment PATCH version. Selected: '${{ inputs.versionIncrementType }}'"
-#          echo "Current branch: ${{ github.ref_name }}"
-#          echo "Selected increment: ${{ inputs.versionIncrementType }}"
-#          echo "LTS branches can only increment PATCH version"
-#          exit 1
+      - name: Validate branch name
+        if: github.ref_name != 'main' && !startsWith(github.ref_name, 'lts/')
+        run: |
+          echo "::error title=Invalid Branch::Branch '${{ github.ref_name }}' is not allowed. Only 'main' or branches starting with 'lts/' are permitted."
+          echo "Error: Invalid branch '${{ github.ref_name }}'"
+          echo "Only 'main' or branches starting with 'lts/' are allowed"
+          exit 1
+
+      - name: Validate LTS branch version increment
+        if: startsWith(github.ref_name, 'lts/') && inputs.versionIncrementType != 'patch'
+        run: |
+          echo "::error title=Invalid Version Increment::LTS branches can only increment PATCH version. Selected: '${{ inputs.versionIncrementType }}'"
+          echo "Current branch: ${{ github.ref_name }}"
+          echo "Selected increment: ${{ inputs.versionIncrementType }}"
+          echo "LTS branches can only increment PATCH version"
+          exit 1
 
       - name: "Checkout"
         uses: actions/checkout@v6
@@ -139,8 +139,8 @@ jobs:
           BRANCH_NAME: ${{ github.ref_name }}
         # language="shell script"
         run: |
-          repositories="https://github.com/Netcracker/qubership-core-config-server[branch=main]
-          https://github.com/Netcracker/qubership-core-core-operator[branch=main]"
+          repositories="https://github.com/Netcracker/qubership-core-config-server[branch=${BRANCH_NAME}]
+          https://github.com/Netcracker/qubership-core-core-operator[branch=${BRANCH_NAME}]"
           echo "repositories=\n${repositories}"
           repositories=$(echo "${repositories}" | tr '\n' ',')
           echo "repositories=${repositories}" >> "${GITHUB_OUTPUT}"
@@ -264,6 +264,7 @@ jobs:
   create-branches:
     needs: release
     if: |
+      github.ref_name == 'main' && 
       inputs.lts_branch_name != '' && 
       startsWith(inputs.lts_branch_name, 'lts/')
     uses: ./.github/workflows/create-branch-from-tag.yaml
