feat: create branch for release

diff --git a/.github/workflows/maven-bulk-release-core-services.yml b/.github/workflows/maven-bulk-release-core-services.yml
--- a/.github/workflows/maven-bulk-release-core-services.yml
+++ b/.github/workflows/maven-bulk-release-core-services.yml
@@ -64,13 +64,13 @@ jobs:
       summary_content: ${{ steps.save-summary.outputs.content }}
 
     steps:
-      - name: Validate branch name
-        if: github.ref_name != 'main' && !startsWith(github.ref_name, 'lts/')
-        run: |
-          echo "::error title=Invalid Branch::Branch '${{ github.ref_name }}' is not allowed. Only 'main' or branches starting with 'lts/' are permitted."
-          echo "Error: Invalid branch '${{ github.ref_name }}'"
-          echo "Only 'main' or branches starting with 'lts/' are allowed"
-          exit 1
+#      - name: Validate branch name
+#        if: github.ref_name != 'main' && !startsWith(github.ref_name, 'lts/')
+#        run: |
+#          echo "::error title=Invalid Branch::Branch '${{ github.ref_name }}' is not allowed. Only 'main' or branches starting with 'lts/' are permitted."
+#          echo "Error: Invalid branch '${{ github.ref_name }}'"
+#          echo "Only 'main' or branches starting with 'lts/' are allowed"
+#          exit 1
 
       - name: Validate LTS branch version increment
         if: startsWith(github.ref_name, 'lts/') && inputs.versionIncrementType != 'patch'
